language: python
python:
    - "3.8"
services:
  - postgresql
install:
- pipenv install
script:
- python manage.py test
before_script:
  - psql -c 'create database globe_trotter_api_test;' -U postgres
  - python3.8 manage.py migrate
