# Generated by Django 3.0.3 on 2020-02-19 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TripDestinationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Destination')),
            ],
        ),
        migrations.RemoveField(
            model_name='tripdestination',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tripdestination',
            name='trip',
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='TripDestination',
        ),
        migrations.AddField(
            model_name='tripdestinationdate',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip_destination_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.TripDestinationDate'),
        ),
    ]
